# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Randi
brief-intro: #Front-end Dev Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sweetlulu486.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links

# twitter_username: 
facebook_username: sobbingcat
github_username:  sweetlulu486
# email: gaohaoyang126@126.com
# weibo_username: 3115521wh
# zhihu_username: gaohaoyang
# linkedIn_username: gaohaoyang
# dribbble_username:

description_footer: 많은 기억보다 작은 기록을

# comments
# two ways to comment, only choose one, and use your own short name
disqus_shortname: sweetlulu486-github

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
